# Generated by Django 4.2.26 on 2025-11-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='field_1',
        ),
        migrations.AddField(
            model_name='post',
            name='field_1',
            field=models.CharField(default='test'),
            preserve_default=False,
        ),
    ]
