# Generated by Django 4.2.26 on 2025-11-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_comment_field_1_post_field_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='field_1',
        ),
    ]
