# Generated by Django 4.2.26 on 2025-11-16 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_field_1'),
        ('blog', '0005_remove_post_field_1_post_field_2_post_field_3'),
    ]

    operations = [
    ]
